apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloggingapp
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
      - name: bloggingapp
        image: farhanawan99/bloggingapp:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: bloggingapp-config
          - secretRef:
              name: bloggingapp-secret


